/*  Create table     */
---------------------------------------------

CREATE TABLE schema_name.table_name (
    column_1 data_type column_constraint,
    column_2 data_type column_constraint,
    ...
    table_constraint
 );

Ex1:

CREATE TABLE ot.persons(
	person_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	first_name VARCHAR2(50) NOT NULL,
	last_name VARCHAR2(50) NOT NULL,
	PRIMARY KEY(person_id));

Ex2:

CREATE TABLE Persons (
    PersonID int,
    LastName varchar(255),
    FirstName varchar(255),
    Address varchar(255),
    City varchar(255)
);


/*Drop table */
-------------------------

DROP TABLE persons;




/*Add Coloumn in the tab*/
-------------------------------------

ALTER TABLE table_name 
ADD column_name data_type constraint;



Ex1: column does not accept NULL

ALTER TABLE members 
ADD birth_date DATE NOT NULL;



Ex2:timestamp with timezone those  columns does not accept null

ALTER TABLE
    members ADD(
        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE NOT NULL
    );

