/*  Create table     */
---------------------------------------------

 

Ex1:

CREATE TABLE ot.persons(
	person_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	first_name VARCHAR2(50) NOT NULL,
	last_name VARCHAR2(50) NOT NULL,
	PRIMARY KEY(person_id));

Ex2:

CREATE TABLE Persons (
    PersonID int,
    LastName varchar(255),
    FirstName varchar(255),
    Address varchar(255),
    City varchar(255)
);


/*Drop table */
-------------------------

DROP TABLE persons;




/*Add Coloumn in the tab*/
-------------------------------------

ALTER TABLE table_name 
ADD column_name data_type constraint;



Ex1: column does not accept NULL

ALTER TABLE members 
ADD birth_date DATE NOT NULL;



Ex2:timestamp with timezone those  columns does not accept null

ALTER TABLE
    members ADD(
        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE NOT NULL
    );





/* Auto increment primary key field of productid in PRODUCT table */
------------------------------------------

CREATE TABLE Product (
    Productid int NOT NULL AUTO_INCREMENT,
    ProductName varchar(255) NOT NULL,
    ProductNumber varchar(255),
    Numberofproducts int,
    PRIMARY KEY (Productid)
);




/* UNIQUE constraint ensures that all values in a column are different */
--------------------------------------------------------

CREATE TABLE Product (
    ID int NOT NULL,
    ProductName varchar(255) NOT NULL,
    ProductNumber varchar(255),
    Numberofproducts int,
    CONSTRAINT UC_Person UNIQUE (ID,ProductNumber)
);




